version: '3.0'
services:
  next:
    restart: always
    container_name: interlinked_next
    build:
      context: ./
      dockerfile: Dockerfile
    command: npm run dev
    volumes:
      - ./:/app/
      - frontend_node_modules:/app/node_modules/
    ports:
      - '3000:3000'
    stdin_open: true

volumes:
  frontend_node_modules:
